name: Feature Request
description: Request a feature
labels: ["Enhancement request", "waits for triage"]
body:
  - type: textarea
    id: desc
    attributes:
      label: Bug description
      description: A more detailled description of the bug
      placeholder: Context for the bug that didn't fit in the title
    validations:
      required: false
